// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/executor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubbmissionId string                 `protobuf:"bytes,1,opt,name=subbmission_id,json=subbmissionId,proto3" json:"subbmission_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSubbmissionId() string {
	if x != nil {
		return x.SubbmissionId
	}
	return ""
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ExecuteResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Stdout       string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr       string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode     int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// SUCCESS, TIME_LIMIT_EXCEEDED, MEMORY_LIMIT_EXCEEDED, RUNTIME_ERROR
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_executor_proto protoreflect.FileDescriptor

const file_api_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/executor.proto\x12\rcode_executor\"g\n" +
	"\x0eExecuteRequest\x12%\n" +
	"\x0esubbmission_id\x18\x01 \x01(\tR\rsubbmissionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\x9b\x01\n" +
	"\x0fExecuteResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2[\n" +
	"\x0fExecutorService\x12H\n" +
	"\aExecute\x12\x1d.code_executor.ExecuteRequest\x1a\x1e.code_executor.ExecuteResponseB-Z+github.com/lindstorm76/code_executor/api/pbb\x06proto3"

var (
	file_api_proto_executor_proto_rawDescOnce sync.Once
	file_api_proto_executor_proto_rawDescData []byte
)

func file_api_proto_executor_proto_rawDescGZIP() []byte {
	file_api_proto_executor_proto_rawDescOnce.Do(func() {
		file_api_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_executor_proto_rawDesc), len(file_api_proto_executor_proto_rawDesc)))
	})
	return file_api_proto_executor_proto_rawDescData
}

var file_api_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_executor_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: code_executor.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: code_executor.ExecuteResponse
}
var file_api_proto_executor_proto_depIdxs = []int32{
	0, // 0: code_executor.ExecutorService.Execute:input_type -> code_executor.ExecuteRequest
	1, // 1: code_executor.ExecutorService.Execute:output_type -> code_executor.ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_executor_proto_init() }
func file_api_proto_executor_proto_init() {
	if File_api_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_executor_proto_rawDesc), len(file_api_proto_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_executor_proto_goTypes,
		DependencyIndexes: file_api_proto_executor_proto_depIdxs,
		MessageInfos:      file_api_proto_executor_proto_msgTypes,
	}.Build()
	File_api_proto_executor_proto = out.File
	file_api_proto_executor_proto_goTypes = nil
	file_api_proto_executor_proto_depIdxs = nil
}
